name: BP2021
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - coverage=5.5
  - coverage-badge=1.1.0
  - flake8=3.9.2
  - gym=0.21.0
  - numpy=1.21.2
  - pre-commit=2.15.0
  - pytest=6.2.4
  - python=3.8.12
  - pytorch=1.10.1
  - pandas=1.3.4
  - matplotlib=3.5.0
  - tensorboard=2.7.0
  - snakeviz=2.1.1
  - pip=21.2.4
  - django=4.0.1
  - uvicorn=0.17.0.post1
  - fastapi=0.73.0
