FROM pure/python:3.8-cuda10.2-runtime

WORKDIR /app
EXPOSE 6006

# Do not buffer stdout so we can see it live
ENV PYTHONUNBUFFERED 1

# copy the src folder and install the pip requirements
RUN python3 -m ensurepip --upgrade
RUN pip install --upgrade pip

COPY ./recommerce ./recommerce
# Install the recommerce package
RUN pip install ./recommerce
# set the datapath and unpack the default data
RUN recommerce --datapath . --get-defaults --unpack --no-action

# Perform the specified action when starting the container
ENTRYPOINT ["recommerce", "-c", "agent_monitoring"]
