name: BP2021
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.21.2
  - python=3.8
  - pytorch
  - flake8
  - pytest
  - gym
  - pre-commit
  - tensorboard
  - coverage
  - coverage-badge 
