# Generated by Django 4.0.1 on 2022-01-26 17:26

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 26, 17, 26, 45, 743876, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='last_check_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
