# Generated by Django 4.0.1 on 2022-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0002_container_created_at_container_last_check_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='health_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
