# Generated by Django 4.0.1 on 2022-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0003_container_health_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.AddField(
            model_name='container',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
