# Generated by Django 4.0.1 on 2022-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0004_remove_container_id_container_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='command',
            field=models.CharField(default='abc', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='tensorboard_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='container',
            name='config_file',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
