# Generated by Django 4.0.1 on 2022-03-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0005_container_command_container_tensorboard_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container_id',
            new_name='id',
        ),
    ]
