# Generated by Django 4.0.1 on 2022-03-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0005_container_command_container_tensorboard_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('agent_class', models.CharField(max_length=100, null=True)),
                ('modelfile', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RlConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamma', models.FloatField(null=True)),
                ('batch_size', models.IntegerField(null=True)),
                ('replay_size', models.IntegerField(null=True)),
                ('learning_rate', models.FloatField(null=True)),
                ('sync_target_frames', models.IntegerField(null=True)),
                ('replay_start_size', models.IntegerField(null=True)),
                ('epsilon_decay_last_frame', models.IntegerField(null=True)),
                ('epsilon_start', models.FloatField(null=True)),
                ('epsilon_final', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimMarketConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage', models.IntegerField(null=True)),
                ('episode_size', models.IntegerField(null=True)),
                ('max_price', models.IntegerField(null=True)),
                ('max_quality', models.IntegerField(null=True)),
                ('number_of_customers', models.IntegerField(null=True)),
                ('production_price', models.IntegerField(null=True)),
                ('storage_cost_per_product', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='container',
            old_name='container_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='HyperparameterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.rlconfig')),
                ('sim_market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.simmarketconfig')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separate_markets', models.BooleanField(null=True)),
                ('episodes', models.IntegerField(null=True)),
                ('plot_interval', models.IntegerField(null=True)),
                ('marketplace', models.CharField(max_length=100, null=True)),
                ('task', models.CharField(choices=[(1, 'training'), (2, 'monitoring'), (3, 'exampleprinter')], max_length=14, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.agentsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.environmentconfig')),
                ('hyperparameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.hyperparameterconfig')),
            ],
        ),
    ]
