# Generated by Django 4.0.1 on 2022-03-18 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0006_agentsconfig_rlconfig_simmarketconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentconfig',
            old_name='agent',
            new_name='agents',
        ),
        migrations.RemoveField(
            model_name='agentsconfig',
            name='agent_class',
        ),
        migrations.RemoveField(
            model_name='agentsconfig',
            name='modelfile',
        ),
        migrations.RemoveField(
            model_name='agentsconfig',
            name='name',
        ),
        migrations.CreateModel(
            name='RuleBasedAgentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_class', models.CharField(max_length=100, null=True)),
                ('argument', models.CharField(max_length=200, null=True)),
                ('agents_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.agentsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='CERebuyAgentQLearningConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_class', models.CharField(max_length=100, null=True)),
                ('argument', models.CharField(max_length=200, null=True)),
                ('agents_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.agentsconfig')),
            ],
        ),
    ]
