# Generated by Django 4.0.1 on 2022-03-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0006_rename_container_id_container_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('agent_class', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFilesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('path_to_file', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RlConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamma', models.FloatField(default=0.99, null=True)),
                ('batch_size', models.IntegerField(default=32, null=True)),
                ('replay_size', models.IntegerField(default=100000, null=True)),
                ('learning_rate', models.FloatField(default=1e-06, null=True)),
                ('sync_target_frames', models.IntegerField(default=1000, null=True)),
                ('replay_start_size', models.IntegerField(default=10000, null=True)),
                ('epsilon_decay_last_frame', models.IntegerField(default=75000, null=True)),
                ('epsilon_start', models.FloatField(default=1.0, null=True)),
                ('epsilon_final', models.FloatField(default=0.1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimMarketConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage', models.IntegerField(default=100, null=True)),
                ('episode_size', models.IntegerField(default=50, null=True)),
                ('max_price', models.IntegerField(default=10, null=True)),
                ('max_quality', models.IntegerField(default=50, null=True)),
                ('number_of_customers', models.IntegerField(default=20, null=True)),
                ('production_price', models.IntegerField(default=3, null=True)),
                ('storage_cost_per_product', models.FloatField(default=0.1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HyperparameterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.rlconfig')),
                ('sim_market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.simmarketconfig')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[(1, 'training'), (2, 'monitoring'), (3, 'exampleprinter')], default='training', max_length=14)),
                ('marketplace', models.CharField(default='market.circular.circular_sim_market.CircularEconomyRebuyPriceMonopolyScenario', max_length=100)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.agentsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.environmentconfig')),
                ('hyperparameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.hyperparameterconfig')),
            ],
        ),
        migrations.AddField(
            model_name='agentsconfig',
            name='modelfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alpha_business_app.modelfilesconfig'),
        ),
    ]
