# Generated by Django 4.0.1 on 2022-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0009_rename_config_file_container_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentconfig',
            name='marketplace',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
