# Generated by Django 4.0.1 on 2022-06-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0012_config_user_container_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentconfig',
            old_name='enable_live_draw',
            new_name='separate_markets',
        ),
    ]
