# Generated by Django 4.0.1 on 2022-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0012_config_user_container_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlconfig',
            name='stable_baseline_test',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='testvalue2',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='batch_size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='epsilon_decay_last_frame',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='epsilon_final',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='epsilon_start',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='gamma',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='learning_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='replay_size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='replay_start_size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rlconfig',
            name='sync_target_frames',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='episode_length',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='max_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='max_quality',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='max_storage',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='number_of_customers',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='production_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='storage_cost_per_product',
            field=models.FloatField(default=None, null=True),
        ),
    ]
