# Generated by Django 4.0.1 on 2022-06-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0013_rename_enable_live_draw_environmentconfig_separate_markets'),
        ('alpha_business_app', '0013_rlconfig_stable_baseline_test_rlconfig_testvalue2_and_more'),
    ]

    operations = [
    ]
