# Generated by Django 4.0.1 on 2022-07-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0014_merge_20220609_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rlconfig',
            old_name='stable_baseline_test',
            new_name='clip_range',
        ),
        migrations.RenameField(
            model_name='rlconfig',
            old_name='testvalue2',
            new_name='ent_coef',
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='buffer_size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='learning_starts',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='n_epochs',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='n_steps',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='neurones_per_hidden_layer',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rlconfig',
            name='tau',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simmarketconfig',
            name='common_state_visibility',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simmarketconfig',
            name='opposite_own_state_visibility',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simmarketconfig',
            name='reward_mixed_profit_and_difference',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
