# Generated by Django 4.0.1 on 2022-07-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0015_rename_stable_baseline_test_rlconfig_clip_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simmarketconfig',
            name='common_state_visibility',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='opposite_own_state_visibility',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='simmarketconfig',
            name='reward_mixed_profit_and_difference',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
