# Generated by Django 4.0.1 on 2022-07-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_business_app', '0016_alter_simmarketconfig_common_state_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmarketconfig',
            name='support_continuous_action_space',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
