name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: CI on ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: BP2021
          auto-update-conda: true
          environment-file: scripts/environment.yml
      - name: Pytest
        shell: bash -l {0}
        run: pytest
      - name: "OnError: Test with pytest (verbose)"
        if: failure()
        shell: bash -l {0}
        run: pytest -v
