name: CI

on: push

jobs:
  build-linux:
    runs-on: [self-hosted, ubuntu-20.04]
    name: CI on Ubuntu
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install AlphaBusiness package
        shell: bash -l {0}
        run: |
          pip install -e ./src
      - name: Pytest
        shell: bash -l {0}
        run: |
          coverage run --source=./src -m pytest
      - name: Report Coverage
        shell: bash -l {0}
        run: |
          coverage report
