name: CI

on: [push, pull_request]

# using setup-miniconda from https://github.com/conda-incubator/setup-miniconda

jobs:
  build:
    runs-on: [self-hosted, ubuntu-20.04]
    name: CI on Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          auto-update-conda: true
          environment-file: scripts/environment.yml
      - name: Pytest
        shell: bash -l {0}
        run: pytest
      - name: "OnError: Test with pytest (verbose)"
        if: failure()
        shell: bash -l {0}
        run: pytest -v
