name: CI

on: push

jobs:
  build-linux:
    runs-on: [self-hosted, ubuntu-20.04]
    name: CI on Ubuntu
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Recommerce package
        shell: bash -l {0}
        run: |
          pip install -e ./
      - name: Setup Recommerce
        shell: bash -l {0}
        run: |
          recommerce --datapath . --get-defaults-unpack
      - name: Pytest
        shell: bash -l {0}
        run: |
          coverage run --source=. -m pytest
      - name: Test Webserver
        shell: bash -l {0}
        run: |
          (cd ./webserver && python ./manage.py test -v 2)
      - name: Report Coverage
        shell: bash -l {0}
        run: |
          coverage report
