name: CI-Matrix

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: CI with MacOS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: base
          auto-update-conda: true
          environment-file: scripts/environment.yml
          python-version: "3.8"
      - name: Pytest
        run: |
          python -m pytest
