name: CI-Matrix

on: [push, pull_request]

jobs:
  example-1:
    name: CI with (${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: scripts/environment.yml
          python-version: ${{ matrix.python-version }}
      - name: Pytest
      - run: |
          python -m pytest
