name: Pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: [self-hosted, ubuntu-20.04]
    name: Pre-commit
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
